language: ruby
dist: trusty
sudo: false
rvm:
  - 2.6.3
before_install:
  - gem install bundler -v 2.0.1
script: bundle exec rake
branches:
  only:
    - master
    - /^v.*$/
deploy:
  provider: rubygems
  api_key:
    secure: b///FmojHLLRY/5KGaCl+JzDq9SEBe8q6V9w6Qg49Jal0/3Fs/aSuRbNiJW/IQFcm0gwZmdSXdU+IO4V2HmqvIWm71iJsFogn9ZHnQuwhmNYXbhtDqFWN6zxVOlouWgk6/TV1lSGpZmVmgNWs3YKMYHBl82pAXAW3Uq0vF1OVvD0j8qtQNb6FpPrXpJvKc1g+TyXHpOYKkIO7PVatJGtgukIAAQyztadgCkN63EQSdkpGZLVyqNipvQyInhES1jC8ZnX5ZjWqmEoG30C3POioqizZr7pRkyFgUKM531QUykq97abz/3PGb46Knq9SVjPAy4tXjeVcq7p1g0J6zFKplKhAw+SohkI59PD5Zu/fZoPYCuHPHzC0r58MFGfLNGZidGtkqXJ1cZZOG1MJanwIg476txa4gEjhj6Y4C/uTXw3Yxu2Nlg7ILLIFe4h/xTFRx7gcnfN7J4jz9JShVxo/DEpQ7juuyg8/uP/S7Eh99K06k090dBJRxNLcbgWw/SINdn2KKMV/eQE1TIGpCqacYrZroZiQo27WbKyigXDcv93NKyZwDofTrxcLe5lDx1dRxjc8rwrBnmCGYKIluCUBvk5rzroAN+7YPWxaVOHE8bFZAquUP526DaoDiwaOCfuxMvFGvxG3YAhkyoLSFI9scMHlMPJjtap/BEkP/aWlmE=
  gem: kontent-jekyll
  on:
    tags: true
    repo: Kentico/kontent-jekyll
